#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    echo 'Project dependencies need to be installed using composer.';
    exit(1);
}

use OckCyp\CoversValidator\Application\CoversValidator;

$app = new CoversValidator;
$app->run();
